- hosts: awsec2
  become: yes
  vars:
  tasks:

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install related Ubuntu packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - python3-pip
          - mc

    - name: Install python packages
      pip:
        name: docker

    - name: Create a Comprobantes network
      docker_network:
        name: mundose_network        
    
    - name: Run Portainer
      community.docker.docker_container:
        name: portainer
        image:  portainer/portainer
        state: started
        restart_policy: always
        env:
          TZ: America/Bogota
        ports:
          - "8000:8000"
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data portainer/portainer
        networks:
          - name: mundose_network
    
    
    
    # - name: Portainer
    #   docker_container:
    #     name: portainer
    #     image: portainer/portainer-ce
    #     state: started
    #     recreate: yes
    #     restart_policy: always
    #     published_ports:
    #       - "8000:8000"
    #       - "9000:9000"
    #     volumes:
    #       - /var/run/docker.sock:/var/run/docker.sock
    #       - portainer_data:/data

