- hosts: awsec2
  become: yes
  roles:
      - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: "438a7a8e1522a4184e8bdb9c3dfb8ab4"
  tasks:

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  
  
    - name: Install related Ubuntu packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - python3-pip
          - mc    

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install python packages
      pip:
        name: docker

    - name: Create a Comprobantes network
      docker_network:
        name: mundose_network        
    
    - name: Run Portainer
      community.docker.docker_container:
        name: portainer
        image:  portainer/portainer
        state: started
        restart_policy: always
        env:
          TZ: America/Bogota
        ports:
          - "8000:8000"
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data portainer/portainer
        networks:
          - name: mundose_network

    - name: Run Postgres
      community.docker.docker_container:
        name: postgres
        image:  postgres:latest
        state: started
        restart_policy: always
        env:
          TZ: America/Bogota
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
        ports:
          - "5432:5432"
        networks:
          - name: mundose_network

    - name: Run SonarQube
      community.docker.docker_container:
        name: sonarqube
        image: sonarqube:9.6-community
        state: started
        restart_policy: always
        env:
          TZ: America/Bogota
          SONARQUBE_JDBC_USERNAME: sonar
          SONARQUBE_JDBC_PASSWORD: sonar
          SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
        ports:
          - "8080:9000"        
        networks:
          - name: mundose_network

    # - name: Run Prometheus
    #   community.docker.docker_container:
    #     name: prometheus
    #     image:  bitnami/prometheus:latest
    #     state: started
    #     restart_policy: always
    #     env:
    #       A

    #     ports:
    #       - "9090:9090"      
    #     networks:
    #       - name: mundose_network    

    # - name: Run Grafana?
    #   community.docker.docker_container:
    #     name: grafana
    #     image:  bitnami/grafana:6
    #     state: started
    #     restart_policy: always
    #     env:
    #       A

    #     ports:
    #       - "3000:3000"      
    #     networks:
    #       - name: mundose_network    
